apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: testing
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - helm:
        images:
          - image: ghcr.io/arishtj/guestbook
            key: image.tag
            value: Tag
            valuesFilePath: guestbook-chart/envs/testing.yaml
      readBranch: HEAD
      writeBranch: HEAD
      repoURL: https://github.com/arishtj/kargo-simple.git
    # If you have an Argo CD application that should be synced after the git repo is updated,
    # uncomment the following lines and specify the app name. Repeat for the other Stages.
    argoCDAppUpdates:
     - appName: guestbook-testing

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: false
      stages:
        - testing
  promotionMechanisms:
    gitRepoUpdates:
      - helm:
          images:
            - image: ghcr.io/arishtj/guestbook
              key: image.tag
              value: Tag
              valuesFilePath: guestbook-chart/envs/staging.yaml
        readBranch: HEAD
        writeBranch: HEAD
        repoURL: https://github.com/arishtj/kargo-simple.git
    # argoCDAppUpdates:
    # - appName: guestbook-staging

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: false
      stages:
        - staging
  promotionMechanisms:
    gitRepoUpdates:
      - helm:
          images:
            - image: ghcr.io/arishtj/guestbook
              key: image.tag
              value: Tag
              valuesFilePath: guestbook-chart/envs/production.yaml
        readBranch: HEAD
        writeBranch: HEAD
        repoURL: https://github.com/arishtj/kargo-simple.git
    # argoCDAppUpdates:
    # - appName: guestbook-prod
