apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/arishtj/kargo-simple.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/arishtj/guestbook
          path: env/dev
    # If you have an Argo CD application that should be synced after the git repo is updated,
    # uncomment the following lines and specify the app name. Repeat for the other Stages.
    # argoCDAppUpdates:
    # - appName: guestbook-dev

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: false
      stages:
        - dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/arishtj/kargo-simple.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/arishtj/guestbook
          path: env/staging
    # argoCDAppUpdates:
    # - appName: guestbook-staging

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: false
      stages:
        - staging
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/arishtj/kargo-simple.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/arishtj/guestbook
          path: env/prod
      pullRequest: {}
    # argoCDAppUpdates:
    # - appName: guestbook-prod
