apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-simple
  namespace: kargo-simple
spec:
  metrics:
    - name: test
      provider:
        job:
          metadata:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: test
                    image: alpine:latest
                    command:
                      - sleep
                      - "10"
                restartPolicy: Never