apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: staging
          - stage: production
  template:
    metadata:
      name: guestbook-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-simple:{{stage}}
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - envs/{{stage}}.yaml
#          parameters:
#            - name: image.tag
#              value: v0.0.1
        repoURL: https://github.com/arishtj/kargo-simple.git
        targetRevision: HEAD
        path: guestbook-chart
      destination:
        server: https://kubernetes.default.svc
        namespace: argo-app
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
#        automated: {}